spring.application.name=elearning-platform
spring.autoconfigure.exclude=org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration

# Server port
server.port=8080

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/elearning_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MaiSonViet2006
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret and Expiration
jwt.secret=4A9hB2y6xV8zL0eN3pM7qR1tW5cU8vI9oX2kG4sF6jE=
# Access token: 15 minutes = 900000 ms
jwt.access-token.expiration=900000
# Refresh token: 14 days = 1209600000 ms
jwt.refresh-token.expiration=1209600000
